//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Thanweya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stage_New_Search
    {
        public int ID { get; set; }
        public int seating_no { get; set; }
        public string arabic_name { get; set; }
        public float total_degree { get; set; }
        public int student_case { get; set; }
        public string student_case_desc { get; set; }
        public float c_flage { get; set; }
    }
}
